version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: release-it
    versions:
    - 14.2.2
    - 14.3.0
    - 14.4.0
    - 14.4.1
    - 14.5.0
    - 14.5.1
  - dependency-name: y18n
    versions:
    - 4.0.1
